version: '3'
services:
  shh-tunnel:
    image: linuxserver/duplicati:latest
    ports:
      - 8200:8200
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - CLI_ARGS=${CLI_ARGS}
    volumes:
      - duplicati-config:/config
      - /backups:/backups # create this folder on your host, i.e. mkdir /backups
      - /source:/source # create this folder on your host, i.e. mkdir /source
    restart: unless-stopped
volumes:
  duplicati-config: