version: '3'
services:
  imgproxy:
    image: darthsim/imgproxy:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_USE_S3: ${IMGPROXY_USE_S3}
      IMGPROXY_S3_ENDPOINT: ${IMGPROXY_S3_ENDPOINT}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}