version: '3'
services:
  shh-tunnel:
    image: linuxserver/openssh-server:latest
    ports:
      - 2222:2222
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - PASSWORD_ACCESS=${PASSWORD_ACCESS}
      - USER_NAME=${USER_NAME}
    volumes:
      - ssh-tunnel-config:/config
volumes:
  ssh-tunnel-config: