version: "3.8"

x-deploy-defaults: &deploy-defaults
  deploy:
    restart_policy:
      condition: on-failure
  platform: ${TARGET_PLATFORM:-}

services:
  mariadb:
    <<: *deploy-defaults
    image: mariadb:11
    healthcheck:
      test: healthcheck.sh --connect --innodb_initialized
      start_period: 10s
      start_interval: 10s
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - mariadb:/var/lib/mysql

  ghost:
    <<: *deploy-defaults
    depends_on:
      mariadb:
        condition: service_healthy
    image: ghost:latest
    environment:
      database__client: mysql
      database__connection__host: mariadb
      database__connection__user: ${DB_USER}
      database__connection__password: ${DB_PASSWORD}
      database__connection__database: ${DB_DATABASE}
    volumes:
      - ghost:/var/lib/ghost/content
    ports:
      - 2368:2368

volumes:
  ghost:
  mariadb: